### ISSUE TITLE
Revert org.apache.struts.tiles2.RedeployableActionServlet

### ISSUE THREAD

**Issue by ste-gr** [ste-gr/struts1-reloaded#33]
### Discussed in https://github.com/weblegacy/struts1/discussions/30

<div type='discussions-op-text'>

<sup>Originally posted by **tdferreira** March 26, 2024</sup>
Hello everyone, it's great to see that some people are actively working on getting Struts up to date. It's certainly important for old projects that for various reason don't want to migrate the tech stack.

I'm not sure this is the right place to ask this, but I see that `org.apache.struts.tiles2.RedeployableActionServlet` has been removed in v1.4.1, is there a reason for this? 
`org.apache.struts.tiles.RedeployableActionServlet` still exists though.

As I don't see anything documented about this, can you clarify what's the alternative servlet-class to add in the web.xml for tiles2?

thank you</div>

**Comment by tdferreira** [comment]
Hello, sorry for the late reply, from my tests it seems to be working just fine ;)

**Comment by ste-gr** [comment]
Hi @tdferreira,

great, thank you for your tests. I will merge it and move it to tiles3 ;-).

Greetings
Stefan
